package main

const serviceTemplate = `// Code generated by DI-generator; DO NOT EDIT.
package di

import (
	{{ .PackageName }} "{{ .PackagePath }}"
	{{- range .Imports }}
	{{ .Alias }} "{{ .Path }}"
	{{- end }}
)

func init() {
	register(func(c *Container) {
		c.Get{{ .Name }}()
	})
}

func (c *Container) Get{{ .Name }}() *{{ .PackageName }}.{{ .Type }} {
	const key = "{{ .Name }}"
	if s, ok := c.services.Load(key); ok {
		return s.(*{{ .PackageName }}.{{ .Type }})
	}

	instance := {{ .PackageName }}.{{ .Func }}(
		{{- range .Props }}
		c.Get{{ .Inject }}(),
		{{- end }}
	)

	s, _ := c.services.LoadOrStore(key, instance)
	return s.(*{{ .PackageName }}.{{ .Type }})
}
`

const baseCode = `// Code generated by DI-generator; DO NOT EDIT.
package di

import "sync"

type Container struct {
	services sync.Map
}

var registry []func(c *Container)

func register(fn func(c *Container)) {
	registry = append(registry, fn)
}

func NewContainer() *Container {
	return &Container{}
}

func (c *Container) InitAll() {
	for _, fn := range registry {
		fn(c)
	}
}`
