package main

const serviceTemplate = `// Code generated by DI-generator; DO NOT EDIT.
package di

import (
	{{ .PackageName }} "{{ .PackagePath }}"
	{{- range .Imports }}
	{{ .Alias }} "{{ .Path }}"
	{{- end }}
)

func init() {
	register(func(c *Container) {
		c.{{ .Name }}()
	})
}

func (c *Container) {{ .Name }}() *{{ .PackageName }}.{{ .Type }} {
	const key = "{{ .Name }}"
	if s, ok := c.services.Load(key); ok {
		return s.(*{{ .PackageName }}.{{ .Type }})
	}

	instance := {{ .PackageName }}.{{ .Func }}(
		{{- range .Props }}
		c.{{ .Inject }}(),
		{{- end }}
	)

	s, _ := c.services.LoadOrStore(key, instance)
	return s.(*{{ .PackageName }}.{{ .Type }})
}
`

const baseCode = `// Code generated by DI-generator; DO NOT EDIT.
package di

import "sync"

var (
	instance *Container
	once     sync.Once
	registry []func(c *Container)
)

type Container struct {
	services sync.Map
}

func register(fn func(c *Container)) {
	registry = append(registry, fn)
}

func GetContainer() *Container {
	once.Do(func() {
		instance = &Container{}
		instance.InitAll()
	})
	return instance
}

func (c *Container) InitAll() {
	for _, fn := range registry {
		fn(c)
	}
}`
