package http

const handlerTemplate = `package {{.PackageName}}

import (
	"context"

	"{{.ImportPath}}"
)

type {{.HandlerName}}Handler struct {
}

// di:new({{.HandlerName}}Handler)
func New{{.HandlerName}}Handler() *{{.HandlerName}}Handler {
	return &{{.HandlerName}}Handler{}
}

{{range .Methods}}
func (h *{{$.HandlerName}}Handler) {{.Name}}({{. | printArgs}}) {{. | printResults}} {
	return nil, nil
}
{{end}}
`

const routerTemplate = `// Code generated by GOR-bridge; DO NOT EDIT.
package http

import (
	"{{.DIPath}}"
	{{range .ModuleImports}}"{{.}}"
	{{end}}
)

type ApiRouter struct {
{{- range .Handlers }}
	*{{.Package}}.{{.StructName}}Handler
{{- end }}
}

func NewApiRouter() *ApiRouter {
	container := di.GetContainer()
	return &ApiRouter{
{{- range .Handlers }}
		{{.StructName}}Handler: container.{{.StructName}}Handler(),
{{- end }}
	}
}
`
